apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: backend
      containers:
        - name: backend
          image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
          ports:
            - containerPort: {{ .Values.deployment.containerPort }}