{{- if .Values.imagePullSecrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.imagePullSecrets.registry (printf "%s:%s" .Values.imagePullSecrets.username .Values.imagePullSecrets.password | b64enc) | b64enc }}
type: kubernetes.io/dockerconfigjson
{{- end }}
