creation_rules:
  - path_regex: 'secrets.yaml'
    age: 'age1ezy0typcf0qepeerq267tzpzv8cs5ffee2ydq002280frgd94fqqr3znjn'
  - path_regex: '.*\.yaml'
    encrypted_regex: '^(stringData|data)$'
    age: 'age1ezy0typcf0qepeerq267tzpzv8cs5ffee2ydq002280frgd94fqqr3znjn'