apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: git@github.com:shiva173/infra.git
    targetRevision: main
    path: apps/backend
    helm:
      valueFiles:
        - values.yaml
        - secrets.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: backend

  syncPolicy:
    automated:
      selfHeal: true
      prune: true