namespace: backend
deployment:
  replicas: 3
  image:
    repository: docker.io/vumnikov/backend
    tag: "3.0.0"
  containerPort: 80

imagePullSecrets:
  create: true
  registry: ""
  username: ""
  password: ""

service:
  type: ClusterIP
  port: 8080
  targetPort: 80

