apiVersion: v1
kind: Secret
metadata:
  name: argocd-infra-repository
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  name: infra
  project: default
  url: git@github.com:shiva173/infra.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACCs1xriLlzYNjDxccizX1erO0g2LOPyJSDKcWXabJPV2QAAAJjRmq4L0Zqu
    CwAAAAtzc2gtZWQyNTUxOQAAACCs1xriLlzYNjDxccizX1erO0g2LOPyJSDKcWXabJPV2Q
    AAAECxgu3yA0CNq/1BtRI6RIDtb4TmuYRqmqUH2q+3VX+YDqzXGuIuXNg2MPFxyLNfV6s7
    SDYs4/IlIMpxZdpsk9XZAAAAE3NoaXZhMTczQHJhbWJsZXIucnUBAg==
    -----END OPENSSH PRIVATE KEY-----

