apiVersion: v1
kind: Secret
metadata:
  name: argocd-infra-repository
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  name: infra
  project: default
  url: git@github.com:shiva173/infra.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    ......
    -----END OPENSSH PRIVATE KEY-----

