apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ2dW1uaWtvdiIsInBhc3N3b3JkIjoiZGNrcl9wYXRfZUJPRXV6dzNZQXd6ZjFPbmEzR1ZocHRKSFBNIiwiYXV0aCI6ImRuVnRibWxyYjNZNlpHTnJjbDl3WVhSZlpVSlBSWFY2ZHpOWlFYZDZaakZQYm1FelIxWm9jSFJLU0ZCTiJ9fX0=
kind: Secret
metadata:
  name: argocd-image-updater-backend
  namespace: argocd
type: kubernetes.io/dockerconfigjson
